test: tc01.sc tc02.sc tc03.sc tc04.sc tc05.sc tc06.sc tc07.sc tc08.sc tc09.sc tc10.sc tc11.sc
	./c6c tc01.sc > tc01.nas
	./c6c tc02.sc > tc02.nas
	./c6c tc03.sc > tc03.nas
	./c6c tc04.sc > tc04.nas
	./c6c tc05.sc > tc05.nas
	./c6c tc06.sc > tc06.nas
	./c6c tc07.sc > tc07.nas
	./c6c tc08.sc > tc08.nas
	./c6c tc09.sc > tc09.nas
	./c6c tc10.sc > tc10.nas
	./c6c tc11.sc > tc11.nas